import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "NextJS file metadata",
    template: "%s | Meta title",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: 'steelblue',
            padding: '1rem',
          }}
        >
          <p>Header</p>
        </header>
          {children}
        <footer
          style={{
            backgroundColor: 'ghostwhite',
            padding: '1rem',
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
